# Generated by Django 6.0.4 on 2026-06-13 13:51

import Music.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_albums', related_query_name='سیو البوم', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to=Music.models.upload_file_to, validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='فایل اهنگ'),
        ),
    ]
