# Generated by Django 6.0.4 on 2026-06-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_album_saved_by_alter_music_music_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_name',
        ),
    ]
