# Generated by Django 6.0.4 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_remove_album_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
